import { Injectable } from '@nestjs/common';
import type {
  FullPlaytestGameState,
  PlayerId,
  StackItem,
} from '@leyline/shared';
import type { PlaytestEvent } from '../game-engine.service';
import type { SpellEffect } from './spell-effect.interface';

/**
 * Registry service for spell effects
 * Manages registration and execution of spell-specific effects
 */
@Injectable()
export class SpellEffectsService {
  private effects: Map<string, SpellEffect> = new Map();

  /**
   * Register a spell effect
   * @param effect - The spell effect to register
   */
  registerEffect(effect: SpellEffect): void {
    this.effects.set(effect.cardName.toLowerCase(), effect);
  }

  /**
   * Register multiple spell effects
   * @param effects - Array of spell effects to register
   */
  registerEffects(effects: SpellEffect[]): void {
    for (const effect of effects) {
      this.registerEffect(effect);
    }
  }

  /**
   * Check if a spell has a registered effect
   * @param cardName - The name of the card
   * @returns True if the card has a registered effect
   */
  hasEffect(cardName: string): boolean {
    return this.effects.has(cardName.toLowerCase());
  }

  /**
   * Execute a spell's effect
   * @param cardName - The name of the card
   * @param state - The current game state
   * @param stackItem - The stack item being resolved
   * @param controller - The player who cast the spell
   * @returns Array of events generated by the effect, or null if no effect registered
   */
  async executeEffect(
    cardName: string,
    state: FullPlaytestGameState,
    stackItem: StackItem,
    controller: PlayerId,
  ): Promise<PlaytestEvent[] | null> {
    const effect = this.effects.get(cardName.toLowerCase());
    if (!effect) {
      return null;
    }

    const result = effect.execute(state, stackItem, controller);
    return result instanceof Promise ? await result : result;
  }

  /**
   * Check if a spell can be cast (beyond mana cost)
   * @param cardName - The name of the card
   * @param state - The current game state
   * @param controller - The player trying to cast the spell
   * @returns True if the spell can be cast, or null if no canCast check registered
   */
  canCast(
    cardName: string,
    state: FullPlaytestGameState,
    controller: PlayerId,
  ): boolean | null {
    const effect = this.effects.get(cardName.toLowerCase());
    if (!effect || !effect.canCast) {
      return null;
    }

    return effect.canCast(state, controller);
  }

  /**
   * Get all registered effect names
   */
  getRegisteredEffects(): string[] {
    return Array.from(this.effects.keys());
  }
}
