import type {
  FullPlaytestGameState,
  PlayerId,
  StackItem,
} from '@leyline/shared';
import type { PlaytestEvent } from '../game-engine.service';

/**
 * Interface for spell effect implementations
 * Each spell that has special effects should implement this interface
 */
export interface SpellEffect {
  /**
   * The exact name of the card this effect handles
   */
  cardName: string;

  /**
   * Execute the spell's effect
   * @param state - The current game state (will be mutated)
   * @param stackItem - The stack item being resolved
   * @param controller - The player who cast the spell
   * @returns Array of events generated by the effect
   */
  execute(
    state: FullPlaytestGameState,
    stackItem: StackItem,
    controller: PlayerId,
  ): Promise<PlaytestEvent[]> | PlaytestEvent[];

  /**
   * Optional: Check if this spell can be cast (beyond mana cost)
   * @param state - The current game state
   * @param controller - The player trying to cast the spell
   * @returns True if the spell can be cast
   */
  canCast?(state: FullPlaytestGameState, controller: PlayerId): boolean;
}
